### ISSUE TITLE
What if the parameters must be integer?

### ISSUE THREAD

**Issue by jiahuanluo** [automl/RoBO#105]
Can I set robo.fmin.bayesian_optimization to select params in integer.
i.e. the param is in a range of [1, 2, 3, 4, 5]

**Comment by aaronkl** [comment]
RoBO cannot handle integer parameters by itself. Instead, you can defining the bounds as [1,5] and then  inside your objective function round it to an integer. Obviously this is somewhat suboptimal since different points in your input space lead to the same integer parameter, but RoBO's model should eventually figure that out.

**Comment by jiahuanluo** [comment]
Thank you!
I will try to compare it with SMAC.
