### ISSUE TITLE
Noise in the observation?

### ISSUE THREAD

**Issue by jbrea** [automl/RoBO#55]
Nice package! I wanted to try it as an alternative to spearmint. 
There I can/have to explicitly define if the observations are noiseless or not (see e.g. https://github.com/HIPS/Spearmint/tree/master/examples/noisy). Do you implicitly assume the noiseless case?

**Comment by aaronkl** [comment]
Hi thanks for using RoBO. No it is not possible to define noiseless observations, but RoBO will figure it out by itself and then only adds a small epsilon on the diagonal of the covariance matrix. In fact also spearmint does not really have a noiseless case as it also adds a small fixed rather than an inferred epsilon on the diagonal. This is commonly done to prevent numerical instabilities and should not make a difference in practice.

**Comment by jbrea** [comment]
Thanks!
