### ISSUE TITLE
entropy_search incumbents

### ISSUE THREAD

**Issue by akamaus** [automl/RoBO#98]
I've a quiestion regarding entropy_search optimizer. 

I see under the hood it's a regular BayesOptimizer with InformationGain acquisition function. Maximums of that function are used for probing original object function. So function is probed not at the points we anticipate it has extreme values but at the points which minimize our uncertainty about minimum point location.

Is it correct to save that points as incumbents as it's done now?

**Comment by aaronkl** [comment]
well it's a bit of an philosophical question: How much do you trust your model?. The reason why we decided to return only the best observed value as incumbent is because we want to be certain about what we return and not relying too much on the model. I think in the original paper they return the maximum of the posterior mean but we found that this sometimes leads to suboptimal results.
